# Generated by Django 3.2.7 on 2022-01-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city_name',
            fields=[
                ('city', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='area_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
                ('city', models.IntegerField()),
            ],
            options={
                'unique_together': {('area', 'city')},
            },
        ),
    ]
