# Generated by Django 3.2.7 on 2022-01-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_sport_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('sport', models.CharField(max_length=50)),
                ('sport_complex', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ground_registration',
            fields=[
                ('ground_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('ground_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=100)),
                ('sport_name', models.CharField(max_length=50)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('rates', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
