# Generated by Django 3.2.7 on 2022-02-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_booking_ground_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground_registration',
            name='ground_image',
            field=models.ImageField(default='', upload_to='myApp/ground_images'),
        ),
    ]
